# Generated by Django 4.0 on 2022-02-16 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myQBank', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='correctnes',
            new_name='correctness',
        ),
    ]
