# Generated by Django 4.0 on 2022-02-24 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myQBank', '0002_rename_correctnes_answer_correctness'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attempted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalAttempts', models.IntegerField(default=0)),
                ('correctAttempts', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myQBank.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myQBank.user')),
            ],
        ),
        migrations.CreateModel(
            name='GrandAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attemptedQuestions', models.ManyToManyField(to='myQBank.Attempted')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myQBank.topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myQBank.user')),
            ],
        ),
    ]
