# Generated by Django 4.0 on 2022-02-24 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myQBank', '0003_attempted_grandattempt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grandattempt',
            name='topic',
        ),
    ]
