# Generated by Django 4.0 on 2022-03-10 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myQBank', '0004_remove_grandattempt_topic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userscourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myQBank.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myQBank.user')),
            ],
        ),
    ]
