# Generated by Django 4.0 on 2022-04-10 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myQBank', '0006_course_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempted',
            name='course',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='myQBank.course'),
        ),
    ]
