# Generated by Django 4.0 on 2022-05-02 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myQBank', '0010_remove_attempted_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempted',
            name='topic',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='myQBank.topic'),
        ),
    ]
