# Generated by Django 4.0 on 2022-07-04 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myQBank', '0015_remove_attempted_topic_attempt'),
    ]

    operations = [
        migrations.CreateModel(
            name='EssayAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='EssayQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('picture', models.URLField(blank=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myQBank.course')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myQBank.topic')),
            ],
        ),
        migrations.CreateModel(
            name='SubQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subQuestion', models.TextField()),
                ('essay_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myQBank.essayanswer')),
                ('essay_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myQBank.essayquestion')),
            ],
        ),
        migrations.AddField(
            model_name='essayanswer',
            name='essay_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myQBank.essayquestion'),
        ),
    ]
