# Generated by Django 4.0 on 2022-07-05 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myQBank', '0017_topic_essay_topic_topic_mcq_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='essayanswer',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
    ]
