# Generated by Django 4.0 on 2022-07-05 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myQBank', '0018_essayanswer_is_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='essayquestion',
            name='has_picture',
            field=models.BooleanField(default=False),
        ),
    ]
