# Generated by Django 4.0 on 2022-07-11 09:19

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('myQBank', '0019_essayquestion_has_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='essayanswer',
            name='answer2',
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
