# Generated by Django 4.0 on 2022-07-11 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myQBank', '0020_essayanswer_answer2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='essayanswer',
            name='answer2',
        ),
    ]
