# Generated by Django 4.0 on 2022-09-09 17:49

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('myQBank', '0021_remove_essayanswer_answer2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essayanswer',
            name='answer',
            field=django_quill.fields.QuillField(),
        ),
        migrations.AlterField(
            model_name='essayquestion',
            name='question',
            field=django_quill.fields.QuillField(),
        ),
    ]
