# Generated by Django 4.0 on 2022-09-09 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myQBank', '0022_alter_essayanswer_answer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='essayquestion',
            name='picture',
        ),
    ]
